kind: pipeline
name: default

steps:
  - name: docker  
    image: plugins/docker
    settings:
        repo: maxkratz/python-custom
        tags: 3.6
        username:
            from_secret: dockerhub_username
        password:
            from_secret: dockerhub_password
    when:
        branch:
            - master
